Matrix multiplication

In [29]:
#matrix multiplication
from numpy import zeros
A = [[1, 2, 3],
     [4, 5, 6]]

B = [[7, 8],
     [9, 10],
     [11, 12]]
def matrix_multiply(A,B):
     row_A,col_A=len(A),len(A[0])
     row_B,col_B=len(B),len(B[0])
     if col_A!=row_B:
          raise ValueError("rows of A and cols of B must match")
     
     C=zeros((row_A, col_B),dtype=int)
     
     for i in range(row_A):
          for j in range(col_B):
               for k in range(row_B):
                    C[i][j]+=A[i][k]*B[k][j]
     return C
matrix_multiply(A,B)

array([[ 58,  64],
       [139, 154]])

Transpose

In [21]:
from numpy import zeros
A = [[1, 2, 3],
     [4, 5, 6]]

C=[[1,0,0],
   [0,1,0],[0,0,1]]
def transpose(A):
     col_A, row_A=len(A[0]),len(A)
     At=zeros((col_A,row_A),dtype=int)
     
     for i in range(row_A):
          for j in range(col_A):
               At[j][i]=A[i][j]
     return At
print(transpose(C))    
print(matrix_multiply(A,transpose(A))) 

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[14 32]
 [32 77]]


Matrix Scalar multiply

In [22]:
import numpy as np
def matrix_scalar(A,n):
     row_A,col_A=len(A),len(A[0])
     B=np.zeros((row_A,col_A),dtype=int)
        
     for i in range(row_A):
          for j in range(col_A):
               B[i][j]=A[i][j]*n
     return B
A = [[1, 2], 
     [3, 4]]
B = [[5, 6], 
     [7, 8]]
n=1
print(matrix_scalar(B,n))
matrix_scalar(matrix_multiply(A,transpose(B)),n)

[[5 6]
 [7 8]]


array([[17, 23],
       [39, 53]])

Matrix exponential

In [11]:
def matrix_exp(A,n):
     row_A,col_A=len(A),len(A[0])
     if row_A!=col_A:
          raise ValueError("rows must match columns")
     if n==0:
          return (1 if i==j else 0 for j in range(col_A) for i in range(row_A))
     elif n==1:
          return A
     exp_A=A
     for _ in range(n-1):
          exp_A=matrix_multiply(exp_A,A)
     return exp_A
matrix_exp(B,0)

<generator object matrix_exp.<locals>.<genexpr> at 0x000001599BBA73E0>

Determinant (Laplace Expansion) and Inverse Matrix

In [29]:
#simple first
matrix = [
    [1, 2, 3],  
    [4, 5, 6],
    [7, 8, 9]
]

col = 1  # Remove column 1 (first col is index 0)
submatrix = [row[:col] + row[col+1:] for row in matrix[1:]]

print(submatrix)
# Output: [[4, 6], [7, 9]]

#MAIN
'''
def determinant_wrong(A):
     if len(A)==1:
          return A
     elif len(A)==2:
          return A[0][0]*A[1][1]-A[1][0]*A[0][1]
     
     det=0
     for col in range(len(A)):
          sub_A=[row[0:col]+row[col+1:] for row in A[1:]]
          cofactor=(-1)**(1+col)*determinant_wrong(sub_A) #this is wrong bcs im too strictly following formula (index: row=1, but index col=0, which will flip the sign of det), the indexing must be consistent, whether both =0 or =1
          det+=A[0][col]*cofactor
     return det
'''
A=[[6, 2, 3],  
    [4, 5, 6],
    [7, 8, 20]]


def determinant_good(A):
     if len(A)==1:
          return A
     elif len(A)==2:
          return A[0][0]*A[1][1]-A[1][0]*A[0][1]
     
     det=0
     for col in range(len(A)):
          sub_A=[row[0:col]+row[col+1:] for row in A[1:]]
          cofactor=(-1)**col*determinant_good(sub_A)
          det+=A[0][col]*cofactor
     return det


det_A=determinant_good(A)

#NUMPY for inverse matrix
import numpy as np
if det_A ==0:
     A_inverse="matrix is singular, no inverse"
else:
     A_inverse=np.linalg.inv(A) #first way of calculating inverse matrix
print("inverse: ",A_inverse)

[[4, 6], [7, 9]]
inverse:  [[ 0.22907489 -0.07048458 -0.01321586]
 [-0.16740088  0.43612335 -0.10572687]
 [-0.01321586 -0.14977974  0.0969163 ]]


Cofactor Matrix -> Abjugate matrix

In [35]:
def cofactor_matrix(A):
     n=A.shape[0]
     cofactor=np.zeros_like(A,dtype=float)
     for i in range(n):
          for j in range(n):
               #create minor by removing row i, col j
               minor=np.delete(np.delete(A,i,axis=0),j, axis=1)
               cofactor[i,j]=(-1)**(i+j)*np.linalg.det(minor)
     return cofactor
def adjugate(A):
     return cofactor_matrix(A).T

B = np.array([[6, 2, 3],  
               [4, 5, 6],
               [7, 8, 20]])  

det_B = np.linalg.det(B)

if np.isclose(det_B, 0):  # Use np.isclose() to check for zero
    print("Matrix B is singular; inverse does not exist.")
else:
    inverse_B_manual = adjugate(B) * (1 / det_B) #second way of calculating inverse matrix
    print("Inverse of B:\n", inverse_B_manual) 

Inverse of B:
 [[ 0.22907489 -0.07048458 -0.01321586]
 [-0.16740088  0.43612335 -0.10572687]
 [-0.01321586 -0.14977974  0.0969163 ]]


Sarrus Determinant

In [7]:
import numpy as np
def sarrus_det(A):
     if A.shape!=(3,3):
          raise ValueError("this only works with 3x3 matrix")
     return (A[0,0]*A[1,1]*A[2,2]+A[0,1]*A[1,2]*A[2,0]+A[0,2]*A[1,0]*A[2,1])-(A[0,1]*A[1,0]*A[2,2]+ A[0, 0] * A[1, 2] * A[2, 1]+A[0, 2] * A[1, 1] * A[2, 0])
A = np.array([[1, 2, 3], 
              [4, 5, 6]])
print(sarrus_det(A))

ValueError: this only works with 3x3 matrix

System of Equations

    Gauss Elimination

In [14]:
import numpy as np
A = np.array([[2, 3, 1],
              [4, 7, 3],
              [6, 18, 5]], dtype=float)

B = np.array([5, 6, 4], dtype=float)
def equa_sys(A,B):
    n=len(A)
    if np.linalg.det(A)==0:
        raise ValueError("the matrix is singular")
    for i in range(n-1):
        for j in range(i+1,n):
            factor = A[j,i]/A[i,i]
            A[j,i:]-=factor*A[i,i:]
            B[j]-=factor*B[i]
    X=np.zeros(n)
    for i in range(n-1,-1,-1):
        X[i]=(B[i]- np.dot(A[i,i+1:],X[i+1:])) / A[i,i]
    return X
equa_sys(A,B)

array([ 4.92857143, -0.42857143, -3.57142857])

    Basic LU Decomposition

In [32]:
A = np.array([
    [2, 3, 1],
    [4, 7, 3],
    [6, 18, 5]
], dtype=float)
def lu_decomposition(A):
    n=len(A)
    L=np.eye(n)
    U=A.astype(float).copy()
    for i in range(n):
        for j in range(i+1,n):
            factor = U[j,i]/U[i,i]
            L[j,i] = factor
            U[j,i:] -= factor * U[i,i:]
    return L,U
L,U = lu_decomposition(A)
print(f"L:\n{L}")
print(f"U:\n{U}")  

matrix_multiply(L,U)

L:
[[1. 0. 0.]
 [2. 1. 0.]
 [3. 9. 1.]]
U:
[[ 2.  3.  1.]
 [ 0.  1.  1.]
 [ 0.  0. -7.]]


array([[ 2,  3,  1],
       [ 4,  7,  3],
       [ 6, 18,  5]])